In [73]:
import pandas as pd
import numpy as np
import math
import time
import yaml
import os

In [83]:
_dh[0]

'D:\\PycharmProjects\\TerraBot\\faction-picker-bot'

In [76]:
dir()

['In',
 'Out',
 '_',
 '_11',
 '_12',
 '_14',
 '_15',
 '_17',
 '_19',
 '_2',
 '_20',
 '_21',
 '_33',
 '_34',
 '_35',
 '_36',
 '_37',
 '_38',
 '_39',
 '_40',
 '_42',
 '_43',
 '_44',
 '_45',
 '_46',
 '_47',
 '_48',
 '_49',
 '_50',
 '_51',
 '_52',
 '_53',
 '_54',
 '_55',
 '_56',
 '_57',
 '_58',
 '_59',
 '_6',
 '_63',
 '_64',
 '_8',
 '_9',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i48',
 '_i49',
 '_i5',
 '_i50',
 '_i51',
 '_i52',
 '_i53',
 '_i54',
 '_i55',
 '_i56',
 '_i57',
 '_i58',
 '_i59',
 '_i6',
 '_i60',
 '_i61',
 '_i62',
 '_i63',
 '_i64',
 '_i65',
 '_i66',
 '_i67',
 '_i68',
 '_i69',
 '_i7',
 '_i70',
 '_i71',
 '_i72',
 '_i73',
 '_i74',
 '_i75',
 '_i76',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'allmermaids',
 'colnames',
 'each_faction_dataset',
 'exit',
 'faction',
 'faction_dataset',
 'factions',
 'featdf',
 'get_ipython',
 'indexes',
 'indexs',
 'math',
 'np',
 'os',
 'pd',
 'quit',
 'time',
 'vpdf',
 'yaml']

In [90]:
script_dir = os.path.dirname(_dh[0])
filename = os.path.join(script_dir, 'params.yaml')

In [91]:
filename

'D:\\PycharmProjects\\TerraBot\\params.yaml'

In [2]:
with open("../params.yaml", 'r') as fd:
    params = yaml.safe_load(fd)

NameError: name 'yaml' is not defined

In [2]:
vpdf = pd.read_csv('D://PycharmProjects/TerraBot/data/faction-picker-bot/vpdata.csv')
featdf = pd.read_csv('D://PycharmProjects/TerraBot/data/faction-picker-bot/featdata.csv')

# split in 12 faction data
vpdf

,Unnamed: 0,game,witches,auren,swarmlings,mermaids,cultists,halflings,dwarves,engineers,chaosmagicians,giants,fakirs,nomads,darklings,alchemists
0,0,0000000001,NaN,NaN,NaN,118.0,NaN,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,050615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122.0,NaN
2,2,0512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124.0,101.0,NaN,NaN,NaN,NaN,NaN
3,3,051501,NaN,84.0,NaN,NaN,NaN,77.0,NaN,NaN,72.0,NaN,NaN,54.0,78.0,NaN
4,4,060303,NaN,NaN,NaN,108.0,NaN,NaN,NaN,121.0,NaN,NaN,78.0,NaN,128.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111541,111541,Youreacrookcaptianhook,NaN,NaN,126.0,NaN,NaN,105.0,NaN,NaN,NaN,NaN,NaN,37.0,NaN,NaN
111542,111542,YourMomIsAChaosMagician,112.0,NaN,114.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.0,NaN,NaN
111543,111543,ytuwertqwtr,NaN,NaN,105.0,NaN,NaN,NaN,102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111544,111544,yuertyqert,128.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.0,NaN,NaN,NaN,NaN,NaN
111545,111545,ZeicheMasZeuchnis,NaN,NaN,NaN,NaN,NaN,NaN,132.0,NaN,NaN,NaN,NaN,88.0,120.0,NaN

In [66]:
colnames = list(vpdf.columns)
factions = [x for x in colnames if x != 'game' and x != 'Unnamed: 0']

In [15]:
indexs = pd.isnull(vpdf['mermaids'])

0         False
1          True
2          True
3          True
4         False
          ...
111541     True
111542     True
111543     True
111544     True
111545     True
Name: mermaids, Length: 111546, dtype: bool

In [62]:
allmermaids = vpdf['mermaids'][~indexs]

In [63]:
allmermaids

0         118.0
4         108.0
6         104.0
9         106.0
21        140.0
          ...
111522     98.0
111525     90.0
111535     68.0
111537     85.0
111538    136.0
Name: mermaids, Length: 33442, dtype: float64

In [64]:
featdf[~indexs]

,Unnamed: 0,game,r1_SCORE1,r1_SCORE2,r1_SCORE3,r1_SCORE4,r1_SCORE5,r1_SCORE6,r1_SCORE7,r1_SCORE8,...,BON8,BON9,BON10,2players,3players,4players,5players,map1,map2,map3
0,0,0000000001,0,0,0,0,0,0,0,1,...,0,1,1,1,0,0,0,1,0,0
4,4,060303,0,1,0,0,0,0,0,0,...,1,1,1,0,0,1,0,0,1,0
6,6,070315,0,1,0,0,0,0,0,0,...,1,1,1,0,0,1,0,1,0,0
9,9,0pandoraravenclaw,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
21,21,16JULY2015,0,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111522,111522,WelcomeFastPlayer,0,0,0,0,1,0,0,0,...,1,1,0,0,0,1,0,1,0,0
111525,111525,WhatsForLunch,0,0,0,0,1,0,0,0,...,1,0,0,1,0,0,0,1,0,0
111535,111535,XiangIsDumb,0,0,1,0,0,0,0,0,...,1,1,0,0,1,0,0,1,0,0
111537,111537,XxxX01,1,0,0,0,0,0,0,0,...,1,0,1,0,1,0,0,1,0,0
111538,111538,Yellowsubmarine,0,0,1,0,0,0,0,0,...,0,1,1,0,1,0,0,1,0,0

In [67]:
each_faction_dataset = {}
for faction in factions:
    faction_dataset = {}
    indexes = pd.isnull(vpdf[faction])
    faction_dataset['vp'] = vpdf[faction][~indexes]
    faction_dataset['features'] = featdf[~indexs]
    each_faction_dataset[faction] = faction_dataset